Import sev-iocuddle and remove shared library code
enarx-archive/sev pull request #62
Opened 2021-08-19 18:35 UTC by tfanelli-rh

Tested on rome hardware.

This cannot be merged until `sev-iocuddle` is pushed to crates.io

2021-08-20 10:32 UTC, haraldh requested changes

2021-08-20 10:32 UTC, haraldh commented on Cargo.toml
> +sev-iocuddle = { git = "https://github.com/tfanelli-rh/sev-iocuddle", branch = "master" }
With this:
```suggestion
sev-iocuddle = { git = "https://github.com/enarx/sev-iocuddle", branch = "master" }
```
the tests pass.

2021-08-24 14:18 UTC, haraldh approved these changes

2021-08-24 14:23 UTC, connorkuehl requested changes
Blocking this until we can depend on a crates.io release instead of a git rev.

2021-09-07 15:44 UTC, closed without merging