fix: simplify snp_launch test
enarx-archive/sev pull request #78
Opened 2021-10-05 11:35 UTC by haraldh

Without `vm_fd.create_irq_chip()` the `hlt` instruction causes a
`KVM_EXIT_HLT`, because no IPIs are expected to wakeup the vCPU from
`hlt`. This opens the possibility to reduce the test case to a simple
`hlt` in the VM and test for a proper `Ok(VcpuExit::Hlt)` for the test
to succeed.

2021-10-05 16:29 UTC, npmccallum requested changes

2021-10-05 16:29 UTC, npmccallum commented on tests/snp_launch.rs
> +        guest_phys_addr: 0,
The address should be a constant. Also, it should probably be something other than zero.

2021-10-05 16:29 UTC, npmccallum commented on tests/snp_launch.rs
> +    regs.rip = std::ptr::null() as *const u64 as u64;
Use the constant.

2021-10-06 09:03 UTC, haraldh commented on tests/snp_launch.rs
> +        guest_phys_addr: 0,
done

2021-10-06 09:03 UTC, haraldh commented on tests/snp_launch.rs
> +    regs.rip = std::ptr::null() as *const u64 as u64;
done

2021-10-07 11:30 UTC, rvolosatovs approved these changes
Looks good, but I think this could be better documented to make it easier to understand for people lacking context/background knowledge (like me)

2021-10-07 11:30 UTC, rvolosatovs commented on tests/snp_launch.rs
> +    const MEM_ADDR: u64 = 0x1000;
Would be nice to add a comment here

2021-10-07 11:30 UTC, rvolosatovs commented on tests/snp_launch.rs
> +    regs.rflags = 2;
Would be nice to add a comment here regarding what this does for people lacking context (like me).
Didn't find anything in Kernel docs and what I understood from https://zserge.com/posts/kvm/ is that this bit should always be set to 1.
If that's the case, how about `0b10` for clarity?

2021-10-07 11:55 UTC, npmccallum commented on tests/snp_launch.rs
> +    const MEM_ADDR: u64 = 0x1000;
That address is where we are going to load the code for execution. It could be anything (but zero should be avoided because `NULL == 0`).

2021-10-07 11:56 UTC, npmccallum commented on tests/snp_launch.rs
> +    regs.rflags = 2;
@rvolosatovs The problem with this stuff is that looks like kvm code at first, until you realize that these are actually just x86 things. So you have to look for documentation there rather than kvm.

`regs.rflags` is just https://en.wikipedia.org/wiki/FLAGS_register

2021-10-07 12:05 UTC, npmccallum commented on tests/snp_launch.rs
> +    regs.rflags = 2;
@rvolosatovs Also, `rip` is the instruction pointer. It points to the next instruction to execute.

If you put all this code together, we load one page full of `hlt` instructions into the VM at guest physical address `MEM_ADDR`. Then we set up the CPU so that `rip` points to the first `hlt` instruction (i.e. at `MEM_ADDR`). Then we enter the VM where the virtual CPU executes the first `hlt` instruction and immediately exits again. The exit reason enum proves that the guest actually exited from the `hlt` instruction and not some other error.

The `rflags` thing is just a paper-cut because x86 CPUs **MUST** always set the second bit in `rflags` to on. This is an annoying x86 thing.

2021-10-07 12:06 UTC, npmccallum approved these changes

2021-10-07 12:14 UTC, merged