move SNP-specific constructs into respective submodule
enarx-archive/sev pull request #79
Opened 2021-10-05 14:02 UTC by rvolosatovs

Closes #74 

1. Since types are renamed and moved in singular commit, blame history seems to be lost - should I split this into 2 separate commits? (although 1 commit seems to look nicer)
2. We still have `Snp.*` at `kvm` module, should we change that as well for consistency?

2021-10-07 08:22 UTC, haraldh approved these changes

2021-10-07 08:29 UTC, rvolosatovs commented
Looks like CI is stuck, I'll try to kick it with an empty commit
![2021-10-07-10:29:08-screenshot](https://user-images.githubusercontent.com/12877905/136348296-4186d09b-6cbf-411e-bad0-bbbfad5c4963.png)

2021-10-07 08:37 UTC, haraldh submitted a review, later dismissed

2021-10-13 11:44 UTC, rvolosatovs commented
@npmccallum need your approval for merge

2021-10-14 17:35 UTC, rvolosatovs commented
Here is the commit based on #90: https://github.com/rvolosatovs/sev/commit/6c8c0b4a45907e0444fd70273c89ab84c6f46121

2021-10-14 19:37 UTC, npmccallum requested changes
I added several comments here about things I'd like to see changed. However, these should be changed in a followup commit since this is a "move code" commit.

2021-10-14 19:37 UTC, npmccallum commented on src/launch/snp.rs
> +}
Hrm... Is there some reason this shouldn't be `impl From<Policy> for u64`?

2021-10-14 19:37 UTC, npmccallum commented on src/launch/snp.rs
> +    pub gosvw: [u8; 16],
Make these private?

2021-10-14 19:37 UTC, npmccallum commented on src/launch/snp.rs
> +    pub vmpl1_perms: VmplPerms,
Private?

2021-10-14 19:37 UTC, npmccallum commented on src/launch/snp.rs
> +    pub host_data: [u8; KVM_SEV_SNP_FINISH_DATA_SIZE],
Private?

2021-10-14 19:42 UTC, rvolosatovs commented
Original intention was to minimize the diff for simpler review and address typing etc. in https://github.com/enarx/sev/issues/83.
I'll address the feedback here and see what's left for that one.

2021-10-15 12:32 UTC, rvolosatovs commented on src/launch/snp.rs
> +    pub gosvw: [u8; 16],
Note: we can't make these completely private, since they are used within `linux` submodule

2021-10-15 14:26 UTC, rvolosatovs commented on src/launch/linux/sev.rs
> +// SPDX-License-Identifier: Apache-2.0
Implementation in this file is not consistent with SNP, but keeping it this way due to:
1. This PR growing in scope
2. SEV functionality and this crate being deprecated *soon* (cc @haraldh)

2021-10-18 17:48 UTC, npmccallum approved these changes

2021-10-18 17:48 UTC, merged